name: Build

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm install -g geolonia/takamatsu-map-cli#main
          takamatsumaps build ./data.csv ./docs

      - name: Deploy the files to `gh-pages`
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
